apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - sumgau/jx
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - sumgau/go
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - sumgau/golang-http
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - sumgau/golang
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - sumgau/node-http-1
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - sumgau/node
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - sumgau/ssample-node-app
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    external_plugins:
      sumgau/go:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      sumgau/golang:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      sumgau/golang-http:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      sumgau/jx:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      sumgau/node:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      sumgau/node-http-1:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      sumgau/ssample-node-app:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      sumgau/go:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      sumgau/golang:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      sumgau/golang-http:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      sumgau/jx:
      - config-updater
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      sumgau/node:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      sumgau/node-http-1:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      sumgau/ssample-node-app:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - sumgau/jx
      trusted_org: sumgau
    - repos:
      - sumgau/go
      trusted_org: sumgau
    - repos:
      - sumgau/golang-http
      trusted_org: sumgau
    - repos:
      - sumgau/golang
      trusted_org: sumgau
    - repos:
      - sumgau/node-http-1
      trusted_org: sumgau
    - repos:
      - sumgau/node
      trusted_org: sumgau
    - repos:
      - sumgau/ssample-node-app
      trusted_org: sumgau
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
