apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: sumgau
    provider: https://github.com
    providerKind: github
    repositories:
    - name: glhttp
    - name: go
    - name: golang
    - name: golang-http
    - name: node
    - name: node-http-1
    - name: node-repo
    - name: ssample-node-app
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
